/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentsPanel: typeof import('./../components/agent/AgentsPanel.vue')['default']
    BaseButton: typeof import('./../components/Form/BaseButton.vue')['default']
    BlockDelegate: typeof import('./../components/chat/blocks/BlockDelegate.vue')['default']
    BlockText: typeof import('./../components/chat/blocks/BlockText.vue')['default']
    BlockThinking: typeof import('./../components/chat/blocks/BlockThinking.vue')['default']
    BlockTool: typeof import('./../components/chat/blocks/BlockTool.vue')['default']
    ChatInput: typeof import('./../components/chat/ChatInput.vue')['default']
    ChatMessages: typeof import('./../components/chat/ChatMessages.vue')['default']
    ChatPanel: typeof import('./../components/agent/ChatPanel.vue')['default']
    CheckboxInput: typeof import('./../components/Form/CheckboxInput.vue')['default']
    ConfirmContainer: typeof import('./../components/Confirm/ConfirmContainer.vue')['default']
    Container: typeof import('./../components/Container.vue')['default']
    ContextMenu: typeof import('./../components/common/ContextMenu.vue')['default']
    ContextMenuItem: typeof import('./../components/common/ContextMenuItem.vue')['default']
    CopilotBubble: typeof import('./../components/copilot/CopilotBubble.vue')['default']
    DangerButton: typeof import('./../components/Form/DangerButton.vue')['default']
    FileTreeNode: typeof import('./../components/agent/FileTreeNode.vue')['default']
    GhostButton: typeof import('./../components/Form/GhostButton.vue')['default']
    HitlApprovalCard: typeof import('./../components/chat/HitlApprovalCard.vue')['default']
    LoadingOverlay: typeof import('./../components/LoadingOverlay.vue')['default']
    LogViewer: typeof import('./../components/LogViewer.vue')['default']
    MessageContainer: typeof import('./../components/Message/MessageContainer.vue')['default']
    MessageItemAssistant: typeof import('./../components/chat/items/MessageItemAssistant.vue')['default']
    MessageItemUser: typeof import('./../components/chat/items/MessageItemUser.vue')['default']
    OutlineButton: typeof import('./../components/Form/OutlineButton.vue')['default']
    OverlayMask: typeof import('./../components/OverlayMask/index.vue')['default']
    Popover: typeof import('./../components/Popover/Popover.vue')['default']
    PopoverContainer: typeof import('./../components/Popover/PopoverContainer.vue')['default']
    Popup: typeof import('./../components/Popup/index.vue')['default']
    PrimaryButton: typeof import('./../components/Form/PrimaryButton.vue')['default']
    ProjectPanel: typeof import('./../components/agent/ProjectPanel.vue')['default']
    RadioInput: typeof import('./../components/Form/RadioInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./../components/Form/SecondaryButton.vue')['default']
    SelectInput: typeof import('./../components/Form/SelectInput.vue')['default']
    SwitchInput: typeof import('./../components/Form/SwitchInput.vue')['default']
    TextButton: typeof import('./../components/Form/TextButton.vue')['default']
    TextInput: typeof import('./../components/Form/TextInput.vue')['default']
    ToolTipContainer: typeof import('./../components/ToolTip/ToolTipContainer.vue')['default']
    Versions: typeof import('./../components/Versions.vue')['default']
    VoicePanel: typeof import('./../components/agent/VoicePanel.vue')['default']
    WorkbenchPanel: typeof import('./../components/agent/WorkbenchPanel.vue')['default']
  }
}
