/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentsPanel: typeof import('./../components/agent/AgentsPanel.vue')['default']
    ChatPanel: typeof import('./../components/agent/ChatPanel.vue')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiFire: typeof import('~icons/mdi/fire')['default']
    IconMdiThumbUp: typeof import('~icons/mdi/thumb-up')['default']
    IconMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    LogViewer: typeof import('./../components/LogViewer.vue')['default']
    ProjectPanel: typeof import('./../components/agent/ProjectPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./../components/Versions.vue')['default']
    VoicePanel: typeof import('./../components/agent/VoicePanel.vue')['default']
    WorkbenchPanel: typeof import('./../components/agent/WorkbenchPanel.vue')['default']
  }
}
