// This file is auto-generated by scripts/generate-api.cjs
// Do not modify this file directly.
/* eslint-disable */

import { invokeBackend } from '@/api/request'

export default {
  chat: {
    agent: {
      chat: (...args: any[]) => {
        return invokeBackend('/api/chat/agent/chat', ...args)
      }
    }
  }
}
